# Generated by Django 5.0.4 on 2024-05-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Name', models.CharField(max_length=20)),
                ('_Age', models.IntegerField()),
                ('_Nickname', models.CharField(max_length=15)),
                ('_level', models.IntegerField(default=0)),
                ('_GameNumbers', models.IntegerField(default=0)),
                ('_GameWin', models.IntegerField(default=0)),
                ('_GameLose', models.IntegerField(default=0)),
                ('_FriendNumbers', models.IntegerField(default=0)),
                ('_BlockList', models.IntegerField(default=0)),
            ],
        ),
    ]
