# Generated by Django 5.0.4 on 2024-05-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamePlayers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userGameInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Nickname', models.CharField(max_length=15)),
                ('level', models.IntegerField(default=0)),
                ('GameNumbers', models.IntegerField(default=0)),
                ('GameWin', models.IntegerField(default=0)),
                ('GameLose', models.IntegerField(default=0)),
                ('FriendNumbers', models.IntegerField(default=0)),
                ('BlockList', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='names',
        ),
    ]
