# Generated by Django 5.0.4 on 2024-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usrInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Clan', models.CharField(max_length=30)),
                ('Level', models.IntegerField(default=0)),
                ('Play', models.IntegerField(default=0)),
                ('Wins', models.IntegerField(default=0)),
                ('Loses', models.IntegerField(default=0)),
                ('Friends', models.IntegerField(default=0)),
            ],
        ),
    ]
