# Generated by Django 5.0.4 on 2024-05-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TheString', models.CharField(max_length=255)),
                ('Describ', models.CharField(max_length=255)),
            ],
        ),
    ]
