# Generated by Django 5.0.4 on 2024-05-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
